app:
  auth:
    stsTokenValidation:
      iss: "https://desk.trial.procivis-one.com"
      jwksUri: "https://desk.trial.procivis-one.com/.well-known/jwks.json"
keyStorage:
  AZURE_VAULT:
    enabled: false
    type: AZURE_VAULT
    params:
      private:
        vaultUrl: "https://procivis-one-demo.vault.azure.net"
        clientId: "9b645db1-39eb-485c-af62-47b3a498bec2"
