format: {}
identifier: {}
issuanceProtocol: {}
verificationProtocol: {}
revocation: {}
did: {}
keyAlgorithm: {}
keyStorage: {}
datatype: {}
task: {}
trustManagement: {}
transport: {}
cacheEntities: {}
holderKeyStorage: {}
blobStorage: {}
walletProvider: {}